name: cairees
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.10.0
    - numpy=1.23.1
    - ffmpeg<7
    - pip=22.3.1
    - pip:
      - https://download.pytorch.org/whl/cu118/torch-2.1.1%2Bcu118-cp310-cp310-linux_x86_64.whl
      - https://download.pytorch.org/whl/cu118/torchvision-0.16.1%2Bcu118-cp310-cp310-linux_x86_64.whl
      - https://download.pytorch.org/whl/cu118/torchaudio-2.1.1%2Bcu118-cp310-cp310-linux_x86_64.whl
      - ffmpeg-python==0.2.0
      - ffprobe-python==1.0.3
      - ipywidgets==8.1.1
      - matplotlib==3.8.2
      - notebook==7.0.6
      - pandas==2.1.3
      - pip-chill==1.0.1
      - plotly==5.18.0
      - umap-learn==0.5.5
      - torchinfo==1.8.0
      - librosa
      - torchmetrics
